// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD3tvd5B8Thg7t94ArTkX8FOVuInV5H4Y',
    appId: '1:540875031007:web:3e27e0eaeddc244a6e046a',
    messagingSenderId: '540875031007',
    projectId: 'nutrition-app-9347f',
    authDomain: 'nutrition-app-9347f.firebaseapp.com',
    storageBucket: 'nutrition-app-9347f.firebasestorage.app',
    measurementId: 'G-QGG9RW7PMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVtH5SUYbz4UbneJfX7Owo8yydxY8XByc',
    appId: '1:540875031007:android:dd4ef22f345f2a4b6e046a',
    messagingSenderId: '540875031007',
    projectId: 'nutrition-app-9347f',
    storageBucket: 'nutrition-app-9347f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbthet_VwiNsWdmz80D0c0_2L0aBp8rxI',
    appId: '1:540875031007:ios:cfb33c260d6a03ff6e046a',
    messagingSenderId: '540875031007',
    projectId: 'nutrition-app-9347f',
    storageBucket: 'nutrition-app-9347f.firebasestorage.app',
    iosBundleId: 'com.example.nutritionTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbthet_VwiNsWdmz80D0c0_2L0aBp8rxI',
    appId: '1:540875031007:ios:cfb33c260d6a03ff6e046a',
    messagingSenderId: '540875031007',
    projectId: 'nutrition-app-9347f',
    storageBucket: 'nutrition-app-9347f.firebasestorage.app',
    iosBundleId: 'com.example.nutritionTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD3tvd5B8Thg7t94ArTkX8FOVuInV5H4Y',
    appId: '1:540875031007:web:1c1c857eaab164816e046a',
    messagingSenderId: '540875031007',
    projectId: 'nutrition-app-9347f',
    authDomain: 'nutrition-app-9347f.firebaseapp.com',
    storageBucket: 'nutrition-app-9347f.firebasestorage.app',
    measurementId: 'G-ZM9VYEQ2L3',
  );
}
